### ISSUE TITLE
Remove me from collaborators

### ISSUE THREAD

**Issue by dmitrc** [dkundel/jacobshack.com#1]
You guys are so willing to go extra measures to completely disassociate us from jacobsHack!, despite us helping to organize it since the very initial idea in the CS Club and following 2 years. And it doesn't matter who was helping and how, it's only you and Naomi being co-founders, right?
I don't want to be associated with this repo. Care to remove me from collaborators, please?

**Comment by ungureanuvladvictor** [comment]
Is this public ?
